### ISSUE TITLE
Changelog is 403 forbidden

### ISSUE THREAD

**Issue by ryandesign** [muflone/jekyll-muflone#1]
On this page:

http://www.muflone.com/jekyll/gwakeonlan/english/

in the sidebar on the right there is a link to "Changelog":

http://www.muflone.com/gwakeonlan/english/changelog.html

but accessing that URL presents this error:

> Access Denied (Forbidden) Error 403
> 
> The requested resource requires an authentication. 
> More information about this error may be available in your cPanel control panel section "Errors".

**Comment by muflone** [comment]
Hi
I've fixed this issue, it was due to my hosting service

Thank you
